app:
  name: "blog"
  mode: "dev"
  port: "8080"
  start_time: "2024-03-27"
  machine_id: 1
auth:
  expire_hour: 168 #一周时间
  encrypt_secret: "lirous.com"
log:
  level: "info"
  filename: "./log/blog.log"
  max_size: 1
  max_age: 30
  max_backups: 7
mysql:
  host: "123.207.217.103"
  username: "root"
  password: "liuzihao520"
  port: "3307"
  dbname: "blog"
  max_open_con: 200
  max_idle_con: 50
redis:
  host: "123.207.217.103"
  port: "16379"
  db: 0
  password: "520liuzihao"
  #  password:
  poll_size: 100
